__CrossEntropyLoss详解__

In [1]:
import torch
import torch.nn.functional as F

#生成神经网络output，一行对应一个样本，一列对应该样本属于该列类的预测概率
output = torch.randn(5, 5)
print('output:\n',output)

#生成5个样本的标签，并转换为One-Hot编码
target = torch.tensor([0, 2, 1, 3, 4])
print('target:\n',target)
one_hot = F.one_hot(target).float()
print('one_hot:\n',one_hot)

#softmax层运算，每个通道每个像素点的值转换为预测概率值
softmax = torch.exp(output)/torch.sum(torch.exp(output),dim=1).reshape(-1, 1)
print('softmax:\n',softmax)

#对数运算，保证数值稳定性和overflaw、underflaw
logsoftmax = torch.log(softmax)
print('logsoftmax:\n',logsoftmax)

#按照label标号为1的像素点位置读取logsoftmax，计算损失函数值
nllloss = -torch.sum(one_hot*logsoftmax)/target.shape[0]
print('one_hot*logsoftmax:\n',one_hot*logsoftmax)
print('nllloss:\n',nllloss)

#直接使用封装好的CrossEntropyLoss计算损失函数值
loss = torch.nn.CrossEntropyLoss()
value = loss(output, target)
print('loss:\n',value)

output:
 tensor([[-0.0106, -0.4310, -1.6414,  1.2071,  0.3368],
        [-0.2920,  1.3862, -1.0200, -0.1568, -1.7095],
        [-0.0953,  0.6084, -0.6550,  0.4059,  0.7989],
        [-1.2834,  0.6305,  0.5013,  1.0222, -0.6259],
        [ 2.5351,  1.5265,  0.5361, -1.2505,  1.2854]])
target:
 tensor([0, 2, 1, 3, 4])
one_hot:
 tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
softmax:
 tensor([[0.1504, 0.0988, 0.0295, 0.5084, 0.2129],
        [0.1216, 0.6511, 0.0587, 0.1392, 0.0295],
        [0.1301, 0.2629, 0.0743, 0.2147, 0.3180],
        [0.0389, 0.2638, 0.2318, 0.3903, 0.0751],
        [0.5526, 0.2016, 0.0749, 0.0125, 0.1584]])
logsoftmax:
 tensor([[-1.8943, -2.3146, -3.5250, -0.6765, -1.5468],
        [-2.1073, -0.4291, -2.8353, -1.9721, -3.5248],
        [-2.0397, -1.3360, -2.5994, -1.5386, -1.1456],
        [-3.2464, -1.3325, -1.4617, -0.9408, -2.5889],
        [-0.5930, -1.6017, 

In [9]:
import torch
import torch.nn.functional as F
target = torch.randint(0, 5, (4, 4))
print(target)
print(target.shape)
one_hot = F.one_hot(target).float()
print(one_hot.shape)
print(one_hot)

tensor([[1, 2, 2, 0],
        [1, 1, 4, 1],
        [0, 3, 4, 2],
        [1, 4, 0, 4]])
torch.Size([4, 4])
torch.Size([4, 4, 5])
tensor([[[0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 1., 0., 0.],
         [1., 0., 0., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 1.],
         [0., 1., 0., 0., 0.]],

        [[1., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.],
         [0., 0., 1., 0., 0.]],

        [[0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 1.],
         [1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1.]]])


__咽喉反流CB_Loss__

In [ ]:
import torch
import math
def cb_loss(y_pred, y_true, temp, beta, confusion):
    confusion_ = [torch.sum(temp == i) for i in range(8)]   #统计一张label中每个类别的像素点

    weight = []
    weight_dice = []
    for i, n in zip(confusion_, confusion):
        if i == 0:
            weight.append(0)
            weight_dice.append(1)
        else:
            weight_dice.append(1)
            weight.append(((1.0 - beta) / (1.0 - math.pow(beta, n))))
    
    
    weight = torch.FloatTensor(weight)
    weight_dice = torch.FloatTensor(weight_dice)
    weight = weight.to(y_pred.device)
    weight_dice = weight_dice.to(y_pred.device)


    criterion_train = torch.nn.CrossEntropyLoss(weight=weight)

    loss = criterion_train(y_pred.float(), temp.float())

    return loss

__CB_Loss__

In [ ]:
import math
import numpy as np

def cb_loss(y_pred, y_true, temp, beta, confusion):
    
    
    #统计标签MASK中每个类的样本数量，temp=y_true
    confusion_ = [torch.sum(temp == i) for i in range(2)]

    weight = []
    weight_dice = []
    for i, n in zip(confusion_, confusion):
        if i == 0:
            weight.append(0)
            weight_dice.append(1)
        else:
            weight_dice.append(1)
            weight.append(((1.0 - beta) / (1.0 - math.pow(beta, n))))
    
    weight = torch.FloatTensor(weight)
    weight_dice = torch.FloatTensor(weight_dice)
    weight = weight.to(y_pred.device)
    weight_dice = weight_dice.to(y_pred.device)


    criterion_train = torch.nn.CrossEntropyLoss(weight=weight)

    loss = criterion_train(y_pred.float(), temp.float())

    return loss




In [7]:
import torch

target = torch.randint(0, 5, (5, 5))
print(target)
confusion_ = [torch.sum(target == i) for i in range(5)]
print(confusion_)

tensor([[2, 3, 3, 1, 2],
        [0, 2, 1, 3, 3],
        [1, 2, 1, 1, 2],
        [2, 0, 3, 0, 0],
        [1, 0, 3, 1, 4]])
[tensor(5), tensor(7), tensor(6), tensor(6), tensor(1)]


__数据集加载最新版本（negative:positive=7:3）（代码保留）__

In [10]:
import os
import glob
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np

class Generate_Dataset1(Dataset):
    def __init__(self, path):
        self.path = path
        self.data_path = glob.glob\
            (os.path.join(path,'negative_input/*.npy'))  #读取data文件夹下所有.npy格式文件

    def __getitem__(self, index):
        data_path = self.data_path[index]
        # print(data_path)
        data = np.load(data_path)      #读取输入数据
        tensor_data = torch.from_numpy(data)
        
        label_path = data_path.replace('input/negative_input', 'label/negative_label')
        label = np.load(label_path)    #读取标签数据
        tensor_label = torch.from_numpy(label)

        return tensor_data, tensor_label

    def __len__(self):
        return len(self.data_path)

class Generate_Dataset2(Dataset):
    def __init__(self, path):
        self.path = path
        self.data_path = glob.glob\
            (os.path.join(path,'positive_input/*.npy'))  #读取data文件夹下所有.npy格式文件

    def __getitem__(self, index):
        data_path = self.data_path[index]
        # print(data_path)
        data = np.load(data_path)      #读取输入数据
        tensor_data = torch.from_numpy(data)
        
        label_path = data_path.replace('input/positive_input', 'label/positive_label')
        label = np.load(label_path)    #读取标签数据
        tensor_label = torch.from_numpy(label)

        return tensor_data, tensor_label

    def __len__(self):
        return len(self.data_path)

#测试载入数据程序
if __name__ == '__main__':


 
    #读取并载入negative_dataset
    print('读入negative_sample...')
    print('***********************************************')
    dataset1 = Generate_Dataset1('../Data/dataset(positive_negative)/input/')
    negative_train_size = int(len(dataset1) * 0.7)
    print('negative_train_size:', negative_train_size)
    negative_validate_size = int(len(dataset1) - negative_train_size)
    print('negative_validate_size:', negative_validate_size)

    negative_train_dataset, negative_validate_dataset = torch.utils.data\
                .random_split(dataset1, [negative_train_size, negative_validate_size])

    print("读入数据个数为：", len(negative_train_dataset))
    print('***********************************************')
    print('读入完毕！')
    print('\n')
    train_loader = DataLoader(negative_train_dataset, batch_size=1, shuffle=True)
    validate_loader = DataLoader(negative_validate_dataset, batch_size=1, shuffle=True)
    
    # t = 0
    # for negative_train, negative_label in train_loader:
    #     t += 1
    #     print(negative_train.shape)
    #     print(negative_label.shape)
    # print('共有',t,'个训练集')
    
    # n = 0
    # for negative_validate, negative_label in validate_loader:
    #     n += 1
    #     print(negative_validate.shape)
    #     print(negative_label.shape)
    # print('共有',n,'个训练集')







    #读取并载入positive_dataset
    print('读入positive_sample...')
    print('***********************************************')
    
    dataset2 = Generate_Dataset2('../Data/dataset(positive_negative)/input/')
    positive_train_size = int(len(dataset2) * 0.7) + 1
    print('positive_train_size:',positive_train_size)
    positive_validate_size = int(len(dataset2) - positive_train_size)
    print('positive_validate_size:', positive_validate_size)
    positive_train_dataset, positive_validate_dataset = torch.utils.data\
                .random_split(dataset2, [positive_train_size, positive_validate_size])

    print("读入数据个数为：", len(positive_train_dataset))
    print('***********************************************')
    print('读入完毕！')
    train_loader = DataLoader(positive_train_dataset, batch_size=1, shuffle=True)
    validate_loader = DataLoader(positive_validate_dataset, batch_size=1, shuffle=True)
    
    
    
    # t = 0
    # for positive_train, positive_label in train_loader:
    #     t += 1
    #     # print(positive_train.shape)
    #     # print(positive_label.shape)
    # # print('共有',t,'个训练集')
    
    # n = 0
    # for positive_validate, positive_label in validate_loader:
    #     n += 1
    #     # print(positive_validate.shape)
    #     # print(positive_label.shape)
    # # print('共有',n,'个训练集')
    print('\n')
    print('开始加载正式数据集...')
    print('***********************************************')
    
    train_dataset = torch.utils.data.ConcatDataset([negative_train_dataset, positive_train_dataset])
    validate_dataset = torch.utils.data.ConcatDataset([negative_validate_dataset, positive_validate_dataset])
    
    # print(len(train_dataset))
    # print(len(validate_dataset))
    # print(list(train_dataset))
    # m = 0
    # for data, label in validate_dataset:
    #     m += 1
    #     # print(data)
    #     print('******************************************************************')
    #     # print(label)
    #     print('一共',m,'个数据')

    
    traindata_Loader = DataLoader(train_dataset, batch_size = 50, shuffle=True)
    validatedata_Loader = DataLoader(validate_dataset, batch_size = 50, shuffle=True)
    q = 0
    for train, label in traindata_Loader:
        # print(train.shape)
        # print(label.shape)
        q += 1
    print('测试集一共划分为：',q,'个批次')
    p = 0
    for validate, label in validatedata_Loader:
        # print(validate.shape)
        # print(label.shape)
        p += 1
    print('验证集一共划分为：',p,'个批次')
    print('***********************************************')
    print('正式数据集加载完毕！')

读入negative_sample...
***********************************************
negative_train_size: 6733
negative_validate_size: 2886
读入数据个数为： 6733
***********************************************
读入完毕！


读入positive_sample...
***********************************************
positive_train_size: 222
positive_validate_size: 95
读入数据个数为： 222
***********************************************
读入完毕！


开始加载正式数据集...
***********************************************
测试集一共划分为： 140 个批次
验证集一共划分为： 60 个批次
***********************************************
正式数据集加载完毕！
